version: '3.8'

services:
  google-drive-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-drive-downloader
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persist downloads
      - ./downloads:/app/downloads
      # Persist task data
      - ./tasks.json:/app/tasks.json
      # Optional: Mount gdown cookies for authentication
      - ~/.cache/gdown:/root/.cache/gdown:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

