version: '3.8'

services:
  google-drive-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-drive-downloader
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      # Persist downloads
      - ./downloads:/app/downloads
      # Persist task data
      - ./tasks.json:/app/tasks.json
      # Persist config data
      - ./config.json:/app/config.json
      # Optional: Mount gdown cookies for authentication (writable)
      - ~/.cache/gdown:/root/.cache/gdown
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

